# coding=utf-8
import os

# ====================================================================
# 參考函數庫
# @dataclass
# class ASRStreamingState:
#     """
#     Streaming ASR state for one audio stream (single utterance).

#     Attributes:
#         unfixed_chunk_num (int):
#             For the first N chunks, do not use previous ASR result as prefix prompt (reset prefix to "").
#         unfixed_token_num (int):
#             When chunk_id >= unfixed_chunk_num, rollback the last K tokens from the accumulated text
#             before using it as prefix prompt, to reduce boundary jitter.
#         chunk_size_sec (float):
#             Chunk size in seconds. Audio will be fed to the model in increments of this length.
#         chunk_size_samples (int):
#             Chunk size in samples at 16kHz (derived from chunk_size_sec).
#         chunk_id (int):
#             Current chunk index (0-based).
#         buffer (np.ndarray):
#             Buffered PCM samples that are not yet consumed into a full chunk.
#         audio_accum (np.ndarray):
#             Accumulated audio from the beginning of the stream up to current time (no padding).
#         prompt_raw (str):
#             Base prompt generated by chat template (with generation prompt), without appended prefix text.
#         context (str):
#             Context string.
#         force_language (Optional[str]):
#             If provided, force output to be text-only by appending "language X<asr_text>" in prompt_raw,
#             consistent with non-streaming transcribe().
#         language (str):
#             Latest parsed language (updated after each chunk decode). Empty if unknown/silent.
#         text (str):
#             Latest parsed transcription text (updated after each chunk decode).
#         _raw_decoded (str):
#             Internal accumulated decoded raw text (before parse_asr_output normalization).
#             Used for rollback/token trimming and as prefix for prompting.
#     """
#     unfixed_chunk_num: int
#     unfixed_token_num: int
#     chunk_size_sec: float
#     chunk_size_samples: int

#     chunk_id: int
#     buffer: np.ndarray
#     audio_accum: np.ndarray

#     prompt_raw: str
#     context: str
#     force_language: Optional[str]

#     language: str
#     text: str
#     _raw_decoded: str

# =====================================================================
# 【讀取本地模型設定】(必須在 import 其他套件前設定)
os.environ["HF_HOME"] = "./qwan_models_cache"
os.environ["HF_HUB_OFFLINE"] = "1"
# =====================================================================

import numpy as np
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
import uvicorn
from contextlib import asynccontextmanager
import json
import logging

from qwen_asr import Qwen3ASRModel

logger = logging.getLogger("uvicorn.error")

# 全域變數，用來存放模型
asr_model = None
ASR_MODEL_PATH = "Qwen/Qwen3-ASR-1.7B"
EXPECTED_SAMPLE_RATE = 24000  # 假設 Windows 傳過來的是 24000Hz

def _resample_to_16k(wav: np.ndarray, sr: int) -> np.ndarray:
    """簡單的重採樣 (24k -> 16k)"""
    if sr == 16000:
        return wav.astype(np.float32, copy=False)
    dur = wav.shape[0] / float(sr)
    n16 = int(round(dur * 16000))
    if n16 <= 0:
        return np.zeros((0,), dtype=np.float32)
    x_old = np.linspace(0.0, dur, num=wav.shape[0], endpoint=False)
    x_new = np.linspace(0.0, dur, num=n16, endpoint=False)
    return np.interp(x_new, x_old, wav).astype(np.float32)

@asynccontextmanager
async def lifespan(app: FastAPI):
    """FastAPI 啟動與關閉時的生命週期管理"""
    global asr_model
    logger.info("正在載入 Qwen3-ASR 模型到 GPU")
    asr_model = Qwen3ASRModel.LLM(
        model=ASR_MODEL_PATH,
        gpu_memory_utilization=0.85,
        max_model_len=4096,
        max_new_tokens=32,
    )
    logger.info("模型載入完成，API 伺服器已啟動")
    yield
    logger.info("伺服器關閉，釋放資源")

app = FastAPI(lifespan=lifespan, title="Qwen3-ASR Streaming API")

def clear_state():
    """清除模型狀態的輔助函式 (如果需要)"""
    global asr_model
    if asr_model is not None:
        asr_model.clear_state()


def _new_streaming_state():
    return asr_model.init_streaming_state(
        unfixed_chunk_num=2,
        unfixed_token_num=5,
        chunk_size_sec=2.0,
    )


async def _finish_and_send(websocket: WebSocket, state, reason: str, notify_client: bool = True):
    logger.info("ASR finish_streaming_transcribe 觸發，reason=%s", reason)
    try:
        asr_model.finish_streaming_transcribe(state)
        logger.info("ASR final result: [%s] %s", state.language, state.text)
        if notify_client:
            await websocket.send_json({
                "status": "final",
                "language": state.language,
                "text": state.text,
                "reason": reason,
            })
    except Exception as e:
        logger.exception("ASR 收尾時發生錯誤: %s", e)
        if notify_client:
            try:
                await websocket.send_json({
                    "status": "error",
                    "language": state.language,
                    "text": state.text,
                    "reason": reason,
                    "message": str(e),
                })
            except Exception:
                logger.info("ASR 無法回傳 error 訊息給 client，可能已斷線")

@app.websocket("/ws/asr")
async def asr_websocket(websocket: WebSocket):
    """處理即時音訊串流的 WebSocket 端點"""
    await websocket.accept()
    logger.info("收到新的語音辨識連線")

    state = _new_streaming_state()
    logger.info("ASR streaming state 初始化完成")
    
    try:
        while True:
            msg = await websocket.receive()

            if msg.get("type") == "websocket.disconnect":
                raise WebSocketDisconnect(code=msg.get("code", 1000))

            if msg.get("text"):
                try:
                    payload = json.loads(msg["text"])
                except json.JSONDecodeError:
                    logger.info("ASR 收到不可解析控制訊息，略過")
                    continue

                if payload.get("type") == "request.finish_stream":
                    await _finish_and_send(websocket, state, payload.get("reason", "pause"))
                    state = _new_streaming_state()
                    logger.info("ASR streaming state 重置，準備下一段語句")
                else:
                    logger.info("ASR 收到未知控制訊息 type=%s", payload.get("type"))
                continue

            audio_bytes = msg.get("bytes")
            if not audio_bytes:
                continue

            # 1. 轉換格式 (Bytes -> int16 -> float32)
            audio_int16 = np.frombuffer(audio_bytes, dtype=np.int16)
            audio_float32 = audio_int16.astype(np.float32) / 32768.0

            # 2. 如果是 24000Hz，降頻為 16000Hz
            wav16k = _resample_to_16k(audio_float32, EXPECTED_SAMPLE_RATE)

            # 3. 餵給 ASR 模型進行推論
            asr_model.streaming_transcribe(wav16k, state)

            # 4. 回傳目前的辨識結果
            await websocket.send_json({
                "status": "streaming",
                "language": state.language,
                "text": state.text
            })

    except WebSocketDisconnect:
        logger.info("ASR 連線已斷開，執行最後收尾")
        await _finish_and_send(websocket, state, "disconnect", notify_client=False)

if __name__ == "__main__":
    # 使用 0.0.0.0 讓外部 (Windows 主機) 可以連入
    uvicorn.run(app, host="0.0.0.0", port=8001)